# Site settings
title: Shuai Zhang's Blog
email: cheungshuai@outlook.com
description: Ph.d Student in UNSW and Data61

# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  cheungdaven
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# 本地用rouge, github上用pygments
highlighter: pygments
# highlighter: rouge
# highlighter: false

# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: shuai zhang
